### ISSUE TITLE
hints for vim users

### ISSUE THREAD

**Issue by ctrngk** [ionelmc/python-hunter#41]
To save output to hunter.log
```bash
PYTHONHUNTER='......' python3 script.py &> hunter.log
```

If you are a vim user, you might want to fold _hunter.log_ by syntax "=>" and "<=" in the 3rd column of output. I have written simple vimscript to do this.  Simply append [the Hunter function](https://gist.github.com/ctrngk/92138847f7e2558eca022ae5eb39b589) to ~/.vimrc

usage:
:call Hunter()

Unfortunately the output file is still plain without any color. My hands are tied. Sorry.

**Comment by ionelmc** [comment]
Try adding an `action=CallPrinter(force_colors=True)`. The defaults are "no tty = no colors".

**Comment by ctrngk** [comment]
I do not understand. I redirect to the plain txt file and the color info will be removed. It is not HTML. Do you have a way saving the log file which contains the color info?

**Comment by ionelmc** [comment]
Because the output redirection stdout won't have a tty attached thus the tty detection fails. Normally people don't want ansi codes in log files (don't cite me on that tho 😁).

So if you insist in having colored output you use `force_colors=True`.

It's like grep output - add another ` | cat` and match highlighting is usually lost.

**Comment by ctrngk** [comment]
I just color the log file in vim, just for easy reading.

![2018-06-07_21-20-55-2](https://user-images.githubusercontent.com/16743578/41102774-3662cb66-6a9a-11e8-84ab-feb297970c4a.gif)
