### ISSUE TITLE
Types supported by `safe_repr`

### ISSUE THREAD

**Issue by GertBurger** [ionelmc/python-hunter#83]
I was wondering what the scope limitations for `safe_repr` is?

Often I run into issues with builtin data types that are not rendered in a usable fashion and if having support for that falls within the scope of `safe_repr` or if the project's opinion is that `repr_func` should be used.

Clearly arbitrary and user defined objects should be handled by a repr func but does python builtins also fall in that category?

**Comment by ionelmc** [comment]
Do you have examples of builtin types that aren't displayed? Note that safe_repr doesn't support subclasses of builtins due to the inherent unsafety of isinstance (it would trigger whatever descriptor is on `__class__` unfortunately). Also see [this](https://blog.ionelmc.ro/2020/01/20/is-there-anything-safe-in-python/).

Hunter could have a `almost_safe_repr`  (that would work like the old repr that used isinstance and such) but I'd like to hear your usecase first.

**Comment by ionelmc** [comment]
Also, search for repr in https://python-hunter.readthedocs.io/en/latest/changelog.html to see how it evolved.

**Comment by GertBurger** [comment]
Right now the ones that I often long for are:

- Most data types in the datetime module: date, time, datetime, timedelta
- Decimal.Decimal
- re.Pattern, so that you can see compiled regexes

I guess one would have to verify that their repr()'s are suitable for inclusion into `safe_repr()` though

**Comment by ionelmc** [comment]
Dully noted. Will add support for those.

**Comment by GertBurger** [comment]
ta, I don't mind doing the work if you are busy...

**Comment by ionelmc** [comment]
Sure, why not 🥳

**Comment by guettli** [comment]
@GertBurger I think this issue was solved via https://github.com/ionelmc/python-hunter/commit/63ed6fd3b35029eac198b859f013e8edf0c77586

Maybe you want to close it?

**Comment by GertBurger** [comment]
:+1:
